#!/bin/bash

# $IMAGE_NAME var is injected into the build so the tag is correct.

echo "Build hook running"
docker build --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
             --build-arg VCS_REF=`wget --spider --force-html -r -l1 \
             http://www.nxfilter.org/download.php 2>&1 \
             | grep '^--' | awk '{ print $3 }' \
             | grep 'nxfilter-' | grep 'zip' \
             | grep -v 'cloud' | head -n1 | \
             cut -d'-' -f 2 | sed "s/.zip//"` \
             -t $IMAGE_NAME .
