#!/bin/bash

# $IMAGE_NAME var is injected into the build so the tag is correct.

echo "Build hook running"
docker build --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
             --label "nxfilter.version=`curl http://www.nxfilter.org/curver.php`" \
             -t $IMAGE_NAME .
